name: Update Word Cloud

on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour
  workflow_dispatch:  # Allows manual execution

jobs:
  run_script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install gspread pandas wordcloud matplotlib google-auth google-auth-oauthlib google-auth-httplib2

      - name: Run Word Cloud Script
        run: python wordcloud_generator.py

      - name: Commit and Push Word Cloud Update
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add wordcloud.png
          git commit -m "Auto-update word cloud"
          git push
